CPKG_NATIVE=1
CPKG_PREFIX=/usr
PKG_SYSETCDIR=/etc
PKG_BINDIR=$CPKG_PREFIX/bin
PKG_SYSLIBDIR=$CPKG_PREFIX/lib
PKG_PCDIR=$PKG_SYSLIBDIR/pkgconfig
PKG_MANDIR=$CPKG_PREFIX/share/man
PKG_SYSSHAREDIR=$CPKG_PREFIX/share
