CPKG_NATIVE=0
CPKG_PREFIX=/opt/pkg
PKG_SYSETCDIR=$CPKG_PREFIX/etc
PKG_BINDIR=$CPKG_PREFIX/bin
PKG_SYSLIBDIR=$CPKG_PREFIX/lib
PKG_PCDIR=$PKG_SYSLIBDIR/pkgconfig
PKG_MANDIR=$CPKG_PREFIX/share/man
PKG_SYSSHAREDIR=$CPKG_PREFIX/share
