% if ((!$PKG_UPDATE && !$PKGSRC_LOCAL_UPDATE)); then
%     OPTS["process"]=0
% else
%     if (($PKG_UPDATE)); then
%         OPTS["rename-to"]="$PKGSRC_DIR/$PKG_CAT/$PKG_NAME/Makefile"
%     elif (($PKGSRC_LOCAL_UPDATE)); then
%         OPTS["rename-to"]="$PKG_CAT/$PKG_NAME/Makefile"
%     fi
# $NetBSD$

PKGNAME=	%{ ${PKG_NAME} }%-%{ ${PKG_VER} }%
CATEGORIES=	%{ ${PKG_CAT} }%
% if (($PKG_FROM_GIT)); then
%     if (($PKG_FROM_GITHUB)); then
MASTER_SITES=   ${MASTER_SITE_GITHUB:=%{ ${PKG_GITHUB_USER} }%/}
GITHUB_PROJECT= %{ ${PKG_NAME} }%
GITHUB_TAG= %{ ${PKG_GIT_COMMIT} }%
DIST_SUBDIR=	%{ ${PKG_NAME} }%
%     fi
% fi
EXTRACT_SUFX=	# none

MAINTAINER=	%{ ${PKG_AUTHOR_EMAIL} }%
COMMENT=	%{ ${PKG_SHORTDESC} }%
LICENSE=	mit
% if ((${#PKG_DEPS[@]})); then

%     for DEP in ${PKG_DEPS[@]}; do
DEPENDS+=	%{ $DEP }%
%     done
% fi

WRKSRC=		${WRKDIR}/%{ ${PKG_NAME} }%-%{ ${PKG_GIT_COMMIT} }%
% CFGFILES=$(cp_find_rel $PKG_SOURCEDIR/etc)
% if [[ -n "$CFGFILES" ]]; then

EGDIR=		${PREFIX}/share/${PKGBASE}/etc/${PKGBASE}
%     for CFGFILE in $CFGFILES; do
CONF_FILES+=	${EGDIR}/%{ $CFGFILE }% \
		${PKG_SYSCONFDIR}/${PKGBASE}/%{ $CFGFILE }%
%     done

OWN_DIRS+=	${PKG_SYSCONFDIR}/${PKGBASE}
% CFGDIRS=$(cp_find_rel $PKG_SOURCEDIR/etc "d")
%     for CFGDIR in $CFGDIRS; do
OWN_DIRS+=	${PKG_SYSCONFDIR}/${PKGBASE}/%{ $CFGDIR }%
%     done
% fi

% if (($CPKG_BUILDING_MYSELF)); then
CPKG=		./cpkg/bin/cpkg
% else
CPKG=		cpkg
% fi

do-configure:
	cd ${WRKSRC} && ${CPKG} configure

.include "../../mk/bsd.pkg.mk"
% fi
